version: '3'

services:
  homecolis-api:
   image: homecolis-api:latest
   hostname: mongo
   environment:
   - ENV=development
   - PORT=8080
   - MONGO_HOST=mongo_db
   - MONGO_PORT=27017
   - MONGO_USER=user
   - MONGO_PASSWORD=password

   ports:
     - 80:8080
   links:
     - mongo_db:mongo_db
   depends_on:
     - mongo_db
   build: .

  mongo_db:
   image: mongo:latest
   environment:
   - NODE_ENV="development"
   - MONGO_HOST=mongo
   - MONGO_PORT=27017
   - MONGO_USER=user
   - MONGO_PASSWORD=password
   - MONGO_DATABASE=test
   command:
    - '--auth'
   volumes:
   - ./data-db:/data/db
{\rtf1}